### ISSUE TITLE
ctlMemoryGetBandwidth does not work with Intel Arc B580

### ISSUE THREAD

**Issue by ProjectPhysX** [intel/drivers.gpu.control-library#120]
`ctlMemoryGetBandwidth` does not work on Battlemage GPUs. `ctl_mem_bandwidth_t::readCounter` and  `ctl_mem_bandwidth_t::writeCounter` always remain `0`.

On Intel Arc A750 it works.

**Comment by pacampbe** [comment]
Hi @ProjectPhysX when you use `ctlMemoryGetBandwidth`, are you setting the version field to 1? The read/write counter data is only populated when the version is 1. If version is 0, only `maxBandwidth` and `timestamp` will be populated.

**Comment by ProjectPhysX** [comment]
@pacampbe yes I've set the version to `1`. Works on Arc A750, broken on Arc B580.
```c
uint memory_count = 0u;
ctlEnumMemoryModules(igcl_devices[i], &memory_count, nullptr);
ctl_mem_handle_t* memory_handle = new ctl_mem_handle_t[memory_count];
ctlEnumMemoryModules(igcl_devices[i], &memory_count, memory_handle);
for(uint j=0u; j<min(memory_count, 1u); j++) {
	ctl_mem_state_t mem_state = { 0 };
	mem_state.Size = sizeof(ctl_mem_state_t);
	ctl_mem_bandwidth_t bandwidth = { 0 };
	bandwidth.Version = 1ul;
	bandwidth.Size = sizeof(ctl_mem_bandwidth_t);
	ctlMemoryGetState(memory_handle[j], &mem_state);
	ctlMemoryGetBandwidth(memory_handle[j], &bandwidth);
	gpus[i].memory_used = (uint)((mem_state.size-mem_state.free)/1048576ull);
	gpus[i].memory_max = (uint)(mem_state.size/1048576ull);
	gpus[i].memory = to_uint(100.0f*(float)(mem_state.size-mem_state.free)/(float)mem_state.size);
	gpus[i].memory_bandwidth_used = (uint)(((bandwidth.readCounter+bandwidth.writeCounter-igcl_last_readwrite[i]))/(bandwidth.timestamp-igcl_last_readwrite_timestamp[i])); // broken on Battlemage
	gpus[i].memory_bandwidth_max =(uint)(bandwidth.maxBandwidth/1000000ull);
	gpus[i].memory_bandwidth = to_uint(100.0f*(float)gpus[i].memory_bandwidth_used/(float)gpus[i].memory_bandwidth_max);
	igcl_last_readwrite[i] = bandwidth.readCounter+bandwidth.writeCounter;
	igcl_last_readwrite_timestamp[i] = bandwidth.timestamp;
}
delete[] memory_handle;
```

**Comment by pacampbe** [comment]
Thanks. I was also able to confirm today that directly reading from the counters on BMG returns a value of 0. I need to investigate and find out if they have either been moved or removed from the BMG telemetry section. The update would be in the form of a kernel mode driver update if a change is required.

**Comment by pacampbe** [comment]
@ProjectPhysX I believe I have fixed the issue with these counters. The change I made is merged into the control library project. It will probably take a few weeks to make it's way through integration with the rest of the driver installation package.

Results from a sample application:
```plaintext
[Memory] Get Memory Bandwidth Version 1:
[Memory] Read Counter (in bytes) [211123574432]
[Memory] Write Counter (in bytes) [5823522048]
[Memory] Max Bandwidth [380000000000]
[Memory] Time Stamp [1463591622]
```

ps: We might also see some other values which were not working, start to work once this update comes.

**Comment by ProjectPhysX** [comment]
@pacampbe fantastic, thank you!

**Comment by ashutosh-d-shukla** [comment]
I am marking this issue as fixed in prod-main-276 based on Paul's update, this should be in public repo in a month's time.

**Comment by ProjectPhysX** [comment]
@ashutosh-d-shukla it's not fixed yet, please reopen this issue.

**Comment by ashutosh-d-shukla** [comment]
Reopened this issue but as I mentioned in my previous comment the fix is yet to be made public in the drivers. Can you confirm which version was used to verify at your end?

**Comment by ProjectPhysX** [comment]
@ashutosh-d-shukla `32.0.101.8626`

**Comment by ashutosh-d-shukla** [comment]
Assigned to Paul who is working on this issue.
